services:
  db:
    image: mysql:9.4.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: backscreen_home
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
