# https://taskfile.dev

version: "3"

tasks:
  default:
    deps: [build]

  build:
    deps: [generate]
    cmds:
      - CGO_ENABLED=0 go build -v -o ./bin/app

  generate:
    cmds:
      - go generate ./...

  test:
    cmds:
      - go test -v -short ./...

  test-all:
    cmds:
      - go test -v -race ./...

  docker-up:
    cmds:
      - docker compose up -d

  docker-down:
    cmds:
      - docker compose down

  docker-clean:
    cmds:
      - docker compose down --volumes

  db:
    cmds:
      - mysql --user root --password=root --host 127.0.0.1 --port 3306 backscreen_home
