# https://taskfile.dev

version: "3"

tasks:
  default:
    deps: [build]

  build:
    deps: [generate]
    cmds:
      - CGO_ENABLED=0 go build -v -o ./bin/app

  generate:
    cmds:
      - go generate ./...

  test:
    cmds:
      - go test -v -short ./...

  test-all:
    cmds:
      - go test -v -race ./...
