openapi: 3.0.0

info:
  title: Currency exchange rates service
  name: currency-exchange-rates
  description: Currency exchange rates service that has two main modes. Fetch rates and server an API to get those.
  version: 0.0.1

paths:
  /api/v1/{currency}:
    get:
      summary: Get latest exchange rate
      parameters:
        - in: path
          name: currency
          schema:
            type: string
          required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Rate"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalServerError"

  /api/v1/{currency}/history:
    get:
      summary: Get all historical exchange rates
      parameters:
        - in: path
          name: currency
          schema:
            type: string
          required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Rate"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalServerError"

components:
  schemas:
    Rate:
      type: object
      required:
        - code
        - value
        - published_at
      properties:
        code:
          type: string
        value:
          type: string
        published_at:
          type: string
          format: date-time
  responses:
    NotFound:
      description: Not found
    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
